#!/usr/bin/env python3
"""Build a frozen, mechanism-discriminating Change Envelope challenge set.

The cases are specified before evaluation.  Visible observations are available
to all methods; held-out observations are used only by the independent safety
oracle.  Configuration candidates are concrete mutations, not generated by the
envelope implementation.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path
from typing import Any, Dict, Iterable, Mapping

ROOT = Path(__file__).resolve().parents[1]
DATA_ROOT = ROOT / "data/msn2026_v81_nontriviality"


def record(device: str, neighbor: str, prefix: str, decision: str, local_pref: int | None) -> Dict[str, Any]:
    return {
        "behavior_id": f"{device}|{neighbor}|{prefix}",
        "device": device,
        "subject": neighbor,
        "fec": prefix,
        "attributes": {"decision": decision, "local_pref": local_pref, "session": "established"},
        "source": "independent_declared_scenario_oracle_v1",
    }


def with_attributes(rows: Iterable[Mapping[str, Any]], changes: Mapping[str, Mapping[str, Any]]) -> list[Dict[str, Any]]:
    output = []
    for original in rows:
        row = json.loads(json.dumps(original))
        row["attributes"].update(changes.get(row["behavior_id"], {}))
        row["source"] = "independent_declared_scenario_oracle_v1_post"
        output.append(row)
    return output


RM_BASE = """hostname edge-latent-rm
!
ip prefix-list PL_TARGET seq 10 permit 10.10.0.0/24
!
route-map RM_SHARED permit 10
 match ip address prefix-list PL_TARGET
 set local-preference 100
!
router bgp 65000
 neighbor 192.0.2.1 remote-as 65101
 neighbor 192.0.2.2 remote-as 65102
 address-family ipv4 unicast
  neighbor 192.0.2.1 activate
  neighbor 192.0.2.2 activate
  neighbor 192.0.2.1 route-map RM_SHARED in
  neighbor 192.0.2.2 route-map RM_SHARED in
 exit-address-family
!
"""

RM_UNSAFE = RM_BASE.replace("set local-preference 100", "set local-preference 250")
RM_SAFE = RM_BASE.replace(
    "route-map RM_SHARED permit 10\n match ip address prefix-list PL_TARGET\n set local-preference 100\n!",
    "route-map RM_SHARED permit 10\n match ip address prefix-list PL_TARGET\n set local-preference 100\n!\n"
    "route-map RM_TARGET_LOCAL permit 10\n match ip address prefix-list PL_TARGET\n set local-preference 250\n!",
).replace("neighbor 192.0.2.1 route-map RM_SHARED in", "neighbor 192.0.2.1 route-map RM_TARGET_LOCAL in")

PL_BASE = """hostname edge-latent-pl
!
ip prefix-list PL_SHARED seq 10 permit 10.30.0.0/24
!
route-map RM_LEFT permit 10
 match ip address prefix-list PL_SHARED
 set local-preference 200
!
route-map RM_RIGHT permit 10
 match ip address prefix-list PL_SHARED
 set local-preference 200
!
router bgp 65000
 neighbor 198.51.100.1 remote-as 65201
 neighbor 198.51.100.2 remote-as 65202
 address-family ipv4 unicast
  neighbor 198.51.100.1 activate
  neighbor 198.51.100.2 activate
  neighbor 198.51.100.1 route-map RM_LEFT in
  neighbor 198.51.100.2 route-map RM_RIGHT in
 exit-address-family
!
"""

PL_UNSAFE = PL_BASE.replace(
    "ip prefix-list PL_SHARED seq 10 permit 10.30.0.0/24",
    "ip prefix-list PL_SHARED seq 10 permit 10.30.0.0/24\n"
    "ip prefix-list PL_SHARED seq 20 permit 10.99.0.0/24",
)
PL_SAFE = PL_BASE.replace(
    "ip prefix-list PL_SHARED seq 10 permit 10.30.0.0/24",
    "ip prefix-list PL_SHARED seq 10 permit 10.30.0.0/24\n"
    "ip prefix-list PL_TARGET_LOCAL seq 10 permit 10.99.0.0/24",
).replace(
    "route-map RM_LEFT permit 10",
    "route-map RM_LEFT permit 5\n match ip address prefix-list PL_TARGET_LOCAL\n"
    " set local-preference 200\n!\nroute-map RM_LEFT permit 10",
)

EXCLUSIVE_BASE = """hostname edge-exclusive
!
ip prefix-list PL_EXCLUSIVE seq 10 permit 172.16.10.0/24
!
route-map RM_EXCLUSIVE permit 10
 match ip address prefix-list PL_EXCLUSIVE
 set local-preference 100
!
router bgp 65000
 neighbor 203.0.113.1 remote-as 65301
 address-family ipv4 unicast
  neighbor 203.0.113.1 activate
  neighbor 203.0.113.1 route-map RM_EXCLUSIVE in
 exit-address-family
!
"""
EXCLUSIVE_SAFE_IN_PLACE = EXCLUSIVE_BASE.replace("set local-preference 100", "set local-preference 275")
EXCLUSIVE_UNSAFE = EXCLUSIVE_BASE.replace(
    "ip prefix-list PL_EXCLUSIVE seq 10 permit 172.16.10.0/24",
    "ip prefix-list PL_EXCLUSIVE seq 10 permit 0.0.0.0/0 le 32",
).replace("set local-preference 100", "set local-preference 275")


def cases() -> list[Dict[str, Any]]:
    rm_visible = [
        record("edge-latent-rm", "192.0.2.1", "10.10.0.0/24", "permit", 100),
        record("edge-latent-rm", "192.0.2.1", "10.20.0.0/24", "implicit-deny", None),
        record("edge-latent-rm", "192.0.2.2", "10.20.0.0/24", "implicit-deny", None),
    ]
    rm_heldout = [record("edge-latent-rm", "192.0.2.2", "10.10.0.0/24", "permit", 100)]
    pl_visible = [
        record("edge-latent-pl", "198.51.100.1", "10.99.0.0/24", "implicit-deny", None),
        record("edge-latent-pl", "198.51.100.1", "10.30.0.0/24", "permit", 200),
        record("edge-latent-pl", "198.51.100.2", "10.50.0.0/24", "implicit-deny", None),
    ]
    pl_heldout = [record("edge-latent-pl", "198.51.100.2", "10.99.0.0/24", "implicit-deny", None)]
    ex_visible = [
        record("edge-exclusive", "203.0.113.1", "172.16.10.0/24", "permit", 100),
        record("edge-exclusive", "203.0.113.1", "172.16.20.0/24", "implicit-deny", None),
    ]
    ex_heldout = [record("edge-exclusive", "203.0.113.1", "172.16.30.0/24", "implicit-deny", None)]
    return [
        {
            "scenario_id": "latent_shared_route_map",
            "device": "edge-latent-rm",
            "baseline": RM_BASE,
            "intent": {
                "intent_id": "rm-target-local-pref",
                "raw_text": "On edge-latent-rm, set local preference 250 only for 10.10.0.0/24 from 192.0.2.1.",
                "selector": {"devices": ["edge-latent-rm"], "subjects": ["192.0.2.1"], "fecs": ["10.10.0.0/24"]},
                "changes": [{"dimension": "local_pref", "relation": "replace", "desired": 250}],
            },
            "visible": rm_visible,
            "heldout": rm_heldout,
            "candidates": [
                {
                    "candidate_id": "unsafe_value_only_shared_edit",
                    "config": RM_UNSAFE,
                    "visible": with_attributes(rm_visible, {rm_visible[0]["behavior_id"]: {"local_pref": 250}}),
                    "heldout": with_attributes(rm_heldout, {rm_heldout[0]["behavior_id"]: {"local_pref": 250}}),
                    "mutation_origin": "value-only mutation of an existing shared route-map",
                },
                {
                    "candidate_id": "safe_local_fork",
                    "config": RM_SAFE,
                    "visible": with_attributes(rm_visible, {rm_visible[0]["behavior_id"]: {"local_pref": 250}}),
                    "heldout": with_attributes(rm_heldout, {}),
                    "mutation_origin": "new local route-map and one target binding change",
                },
            ],
        },
        {
            "scenario_id": "latent_shared_prefix_list",
            "device": "edge-latent-pl",
            "baseline": PL_BASE,
            "intent": {
                "intent_id": "pl-target-admission",
                "raw_text": "On edge-latent-pl, permit 10.99.0.0/24 from 198.51.100.1 with local preference 200 only.",
                "selector": {"devices": ["edge-latent-pl"], "subjects": ["198.51.100.1"], "fecs": ["10.99.0.0/24"]},
                "changes": [
                    {"dimension": "decision", "relation": "replace", "desired": "permit"},
                    {"dimension": "local_pref", "relation": "replace", "desired": 200},
                ],
            },
            "visible": pl_visible,
            "heldout": pl_heldout,
            "candidates": [
                {
                    "candidate_id": "unsafe_shared_match_expansion",
                    "config": PL_UNSAFE,
                    "visible": with_attributes(pl_visible, {pl_visible[0]["behavior_id"]: {"decision": "permit", "local_pref": 200}}),
                    "heldout": with_attributes(pl_heldout, {pl_heldout[0]["behavior_id"]: {"decision": "permit", "local_pref": 200}}),
                    "mutation_origin": "new permit entry in an existing shared prefix-list",
                },
                {
                    "candidate_id": "safe_target_clause",
                    "config": PL_SAFE,
                    "visible": with_attributes(pl_visible, {pl_visible[0]["behavior_id"]: {"decision": "permit", "local_pref": 200}}),
                    "heldout": with_attributes(pl_heldout, {}),
                    "mutation_origin": "target-exclusive route-map clause using a new prefix-list",
                },
            ],
        },
        {
            "scenario_id": "target_exclusive_in_place",
            "device": "edge-exclusive",
            "baseline": EXCLUSIVE_BASE,
            "intent": {
                "intent_id": "exclusive-target-local-pref",
                "raw_text": "On edge-exclusive, set local preference 275 for 172.16.10.0/24 from 203.0.113.1.",
                "selector": {"devices": ["edge-exclusive"], "subjects": ["203.0.113.1"], "fecs": ["172.16.10.0/24"]},
                "changes": [{"dimension": "local_pref", "relation": "replace", "desired": 275}],
            },
            "visible": ex_visible,
            "heldout": ex_heldout,
            "candidates": [
                {
                    "candidate_id": "safe_exclusive_in_place",
                    "config": EXCLUSIVE_SAFE_IN_PLACE,
                    "visible": with_attributes(ex_visible, {ex_visible[0]["behavior_id"]: {"local_pref": 275}}),
                    "heldout": with_attributes(ex_heldout, {}),
                    "mutation_origin": "value-only edit of a target-exclusive route-map",
                },
                {
                    "candidate_id": "unsafe_match_widening",
                    "config": EXCLUSIVE_UNSAFE,
                    "visible": with_attributes(
                        ex_visible,
                        {
                            ex_visible[0]["behavior_id"]: {"local_pref": 275},
                            ex_visible[1]["behavior_id"]: {"decision": "permit", "local_pref": 275},
                        },
                    ),
                    "heldout": with_attributes(ex_heldout, {ex_heldout[0]["behavior_id"]: {"decision": "permit", "local_pref": 275}}),
                    "mutation_origin": "overbroad match plus value edit",
                },
            ],
        },
    ]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build(output_root: Path = DATA_ROOT) -> Dict[str, Any]:
    if output_root.exists():
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True)
    files = []
    for scenario in cases():
        root = output_root / "scenarios" / scenario["scenario_id"]
        (root / "baseline").mkdir(parents=True)
        (root / "baseline" / f"{scenario['device']}.conf").write_text(scenario["baseline"], encoding="utf-8")
        (root / "intent.json").write_text(json.dumps(scenario["intent"], indent=2, sort_keys=True) + "\n", encoding="utf-8")
        (root / "visible_pre_observations.json").write_text(json.dumps(scenario["visible"], indent=2, sort_keys=True) + "\n", encoding="utf-8")
        (root / "heldout_pre_observations.json").write_text(json.dumps(scenario["heldout"], indent=2, sort_keys=True) + "\n", encoding="utf-8")
        (root / "scenario.json").write_text(
            json.dumps(
                {
                    "scenario_id": scenario["scenario_id"],
                    "freeze_version": "v81-nontriviality-1.0.0",
                    "visible_to_methods": ["baseline/", "intent.json", "visible_pre_observations.json"],
                    "oracle_only": ["heldout_pre_observations.json", "candidates/*/heldout_post_observations.json"],
                    "construction": "predeclared mechanism challenge; no envelope output used in candidate construction",
                },
                indent=2,
                sort_keys=True,
            ) + "\n",
            encoding="utf-8",
        )
        for candidate in scenario["candidates"]:
            candidate_root = root / "candidates" / candidate["candidate_id"]
            (candidate_root / "configs").mkdir(parents=True)
            (candidate_root / "configs" / f"{scenario['device']}.conf").write_text(candidate["config"], encoding="utf-8")
            (candidate_root / "visible_post_observations.json").write_text(json.dumps(candidate["visible"], indent=2, sort_keys=True) + "\n", encoding="utf-8")
            (candidate_root / "heldout_post_observations.json").write_text(json.dumps(candidate["heldout"], indent=2, sort_keys=True) + "\n", encoding="utf-8")
            (candidate_root / "candidate.json").write_text(
                json.dumps(
                    {
                        "candidate_id": candidate["candidate_id"],
                        "mutation_origin": candidate["mutation_origin"],
                        "generated_without_envelope": True,
                        "expected_verdict_hidden_from_methods": True,
                    },
                    indent=2,
                    sort_keys=True,
                ) + "\n",
                encoding="utf-8",
            )
    for path in sorted(output_root.rglob("*")):
        if path.is_file():
            files.append({"path": path.relative_to(output_root).as_posix(), "sha256": sha256(path), "bytes": path.stat().st_size})
    manifest = {
        "dataset_id": "msn2026_v81_nontriviality",
        "version": "1.0.0",
        "seed": 8102026,
        "source": "fresh predeclared synthetic brownfield mechanism challenges",
        "license": "project-generated research artifact",
        "scenario_count": len(cases()),
        "candidate_count": sum(len(item["candidates"]) for item in cases()),
        "files": files,
    }
    (output_root / "dataset_manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


if __name__ == "__main__":
    print(json.dumps(build(), indent=2, sort_keys=True))
